# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.18-cli-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
        
      - run: sudo apt-get install -y libcurl4-openssl-dev libsqlite3-dev libicu-dev libsqlite3-0 libsqlite3-dev sqlite3
      - run: sudo apt-get install -y zlib1g-dev libssl-dev libmcrypt-dev libpng-dev libjpeg62-turbo-dev g++  build-essential
      - run: sudo apt-get install -y libfreetype6-dev libmemcached-dev 
      - run: sudo docker-php-ext-install zip mcrypt mysqli curl gd gettext intl mbstring pdo pdo_mysql pdo_sqlite

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - run: php composer-setup.php
      - run: php -r "unlink('composer-setup.php');"
      - run: php composer.phar self-update
      - run: sudo mv composer.phar /usr/local/bin/composer
      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: vendor/bin/phpunit